import Head from "next/head";

import Navbar from "../src/index/navbar/index";
import Content from "../src/index/content/content";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Entre Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Content />
    </div>
  );
}
